#!/usr/bin/env bash
#installig nginx and setting rersponse to "Hellow world"
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo servicw nginx restart
